### ISSUE TITLE
MSpec output not showing the behaviors

### ISSUE THREAD

**Issue by SoyUnEmilio** [machine-visualstudio/machine.vstestadapter#13]
------ Prueba de ejecución iniciada ------
Machine Specifications Visual Studio Test Adapter - Executing Specifications.
Machine Specifications Visual Studio Test Adapter - Executing tests in C:\Users\emilio\documents\visual studio 2013\Projects\Worx.BDD\Wrox.BDD.Specs.Core\bin\Debug\Wrox.BDD.Specs.Core.dll
Machine Specifications Visual Studio Test Adapter - Execution Complete - 2 specifications in 1 assemblies.
========== Prueba de ejecución finalizada: 2 ejecutó (0:00:00,3212122) ==========

And I was expecting something like this:
------ Prueba de ejecución iniciada ------
...
...
TicTacToeGamePresenter, when starting a new game
  should send a welcome message to the view
  should prompt for a move
Machine Specifications Visual Studio Test Adapter - Execution Complete - 2 specifications in 1 assemblies.
========== Prueba de ejecución finalizada: 2 ejecutó (0:00:00,3212122) ==========

**Comment by ivanz** [comment]
Closing this in favour of #36, which will be used to track this.
