### ISSUE TITLE
Test explorer window does not show behabiors in order

### ISSUE THREAD

**Issue by SoyUnEmilio** [machine-visualstudio/machine.vstestadapter#14]
In Test Explorer I see the test names in alphabetical order and not in the order I have declared them in the spec file (I'm groping tests by class in the test explorer).

In test explorer I am viewing:
when_starting_a_new_game
should prompt for a move
should send a welcome message to the view

And in the class when_starting_a_new_game first comes "should send a welcome message to the view" and "then should prompt for a move".

![behavior order](https://cloud.githubusercontent.com/assets/1872807/6033953/fef264dc-ac1c-11e4-9cea-65fd9c2cc46a.png)

**Comment by ivanz** [comment]
Unfortunately the Visual Studio extensibility api doesn't provide any way to tell it how to order the tests and always sorts alphabetically, so there is nothing we can do.
