### ISSUE TITLE
Fatal Exception when Spec Contains Bahaves_Like

### ISSUE THREAD

**Issue by JarrodJ83** [machine-visualstudio/machine.vstestadapter#18]
I tried to start using behaviors in my specs and as soon as I did I started getting this exception when I try to run or debug my tests via the VS Test Adapter. If I comment out the Behaves_Like and put the assertion directly in my spec things work fine. 

So, this works fine:

```c#
public class Event_Spec
{
     protected static MemoryCallSvc CallSvc;
     // omitted out code for brevity

     It sends_an_event = () => CallSvc.Calls.Any();
     //Behaves_like<An_Event_Was_Raised> an_event_has_been_sent;
}
```

but this causes the exception:

```c#
public class Event_Spec
{
     protected static MemoryCallSvc CallSvc;
     // omitted out code for brevity

     //It sends_an_event = () => CallSvc.Calls.Any();
     Behaves_like<An_Event_Was_Raised> an_event_has_been_sent;
}
```

here is my behavior:

```c#
[Behaviors]
public class An_Event_Was_Raised
{
     protected static MemoryCallSvc CallSvc;

     It sends_an_event = () => CallSvc.Calls.Any();
}
```

Here is my visual studio info:
Microsoft Visual Studio Ultimate 2013
Version 12.0.31101.00 Update 4
Microsoft .NET Framework
Version 4.5.51650

I'm using MSpec v0.7.0

It's also worth noting that the tests run fine even when using behviors if run by using mspec.exe from the command line.

**Comment by JarrodJ83** [comment]
Just noticed that behavior support is still on the "to do" list. If it helps, I think the issue at hand, at least with this particular issue, is the test explorer doesn't list the assertion from the specs that leverage the behavior but rather lists the behavior itself.

**Comment by JonathanWilkins** [comment]
Thanks will hopefully get onto this soon

**Comment by ivanz** [comment]
Closing this in favour of #36, which will be used to track this.
