### ISSUE TITLE
adapter not reporting output tp vstest.console properly

### ISSUE THREAD

**Issue by simoncalvin** [machine-visualstudio/machine.vstestadapter#20]
I'm trying to get my VS Online build to exercise mspec tests. I've added the binaries from the VSIX into my repo (it's git, if that matters) and set the "Path to custom test adapters" setting to their location. When the test step of my build executes the following message appears in the log:

"Warning: The path 'C:\a\c8651a29\Configure\Machine.VSTestAdapter\' specified in the 'TestAdapterPath' does not contain any test adapters, provide a valid path and try again."

I am able to discover the nUnit adapter using the same method, so I'm confident that my build definition isn't the problem.

I've been trying to figure out if something is missing that might cause this. The documentation available from MS is laughably scarce (as you're probably aware). My only thought at this point is that it might be the fact that there is no TestContainerDiscoverer in machine.vstestadapter. I'll investigate the possibility, but if you have any insight I'd love to hear it. Thanks!

**Comment by JonathanWilkins** [comment]
I'll have a look into it, I've been trying to get the adapter to run from a nuget package and had similar issues, so could very well be related.

**Comment by simoncalvin** [comment]
Quick update: the TestContainerDiscoverer is a non-starter. The nUnit adapter works fine without one.

**Comment by simoncalvin** [comment]
With the help of Terje Sandstrom from the nUnit adapter team, I figured out why it's not getting picked up by the build server. Turns out that the adapter assembly name must end in ".TestAdapter.dll"  (NB: preceding period) in order for it to be recognized by vstest.console.exe which is how TFS build invokes the tests. Naming conventions strike again :)

Unfortunately, after fixing that I'm running into another issue. It appears as though the adapter isn't reporting results back to vstest.console properly. Here's the output from running against an test assembly that contains one intentionally failing spec: 

>Starting test execution, please wait...
>Information: Machine Specifications Visual Studio Test Adapter - Discovering Specifications.

>Information: Machine Specifications Visual Studio Test Adapter - Discovering...looking in C:\src\vso\Configure\Configure.Tests.Unit\bin\Debug\Configure.Tests.Unit.dll

>Information: Machine Specifications Visual Studio Test Adapter - Discovery Complete - 1 specifications in 1 of 1 assemblies scanned.

>Information: Machine Specifications Visual Studio Test Adapter - Executing Specifications.

>Information: Machine Specifications Visual Studio Test Adapter - Executing tests in C:\src\vso\Configure\Configure.Tests.Unit\bin\Debug\Configure.Tests.Unit.dll

>Information: Machine Specifications Visual Studio Test Adapter - Execution Complete - 1 specifications in 1 assemblies.

>Warning: No test is available in the provided sources. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.

>Information: Additionally, you can try specifying '/UseVsixExtensions' command if the test discoverer & executor is installed on the machine as vsix extensions and your installation supports vsix extensions. Example: vstest.console.exe myTests.dll /UseVsixExtensions:true

I get a similar result when I run the tests as part of the VS Online build, only the messages from the adapter are omitted (I assume due to verbosity level).

So the question at this point is: do you want to close this issue with the name change and open a new one for this new thing. Or would you prefer that I edit this issue to reflect that the adapter isn't working right in the console runner? 

By the way, I would be happy to provide a PR to fix the assembly name problem. Do you want it to be Machine.TestAdapter? Machine.VisualStudio.TestAdapter?

**Comment by JonathanWilkins** [comment]
changed the name of this issue will try and sort that out for you, will probably only be able to get a chance to have a look nearer the end of the week

**Comment by JonathanWilkins** [comment]
Don't stress about the PR I've been trying to get this thing to run from a nuget package so have actually changed the name already, hoping  to have that sorted soon.
Lets hope it sorts things out for you to.

**Comment by simoncalvin** [comment]
Awesome. I'm going to continue to poke around as well. I'll let you know if I find anything.

**Comment by marketinvoiceit** [comment]
What's the status of this? I am about to start looking into making my Mspec tests run in the new Visual Studio Online build system.

**Comment by ivanz** [comment]
What is the status of this? I am just about to start looking into running my MSpec tests in the new Visual Studio Online build system.

**Comment by JonathanWilkins** [comment]
Hi I haven't been able to look any further into this as yet hoping to get there in the coming weeks

**Comment by ivanz** [comment]
@JonathanWilkins If you can give me any pointers as to where to start from - I am happy to try and have a look at this too. I assume the NUnit test adaptor works in VSO, so maybe pointers to what is implemented there vs what is missing in the mspec adaptor?

**Comment by JonathanWilkins** [comment]
As far as I understand it does, that's really all I've been doing is trying to compare Nunit to what we have and see what might be missing. I know the one difference was the Assembly naming which we have sorted. Not sure what else it might be. If you want to take a look that would be a huge help.

**Comment by ivanz** [comment]
I have successfully been able to run mspec tests in VSO (now VS Team Services) with the shortly to be released 1.7.0 nuget package and test output works fine. Tests show up in the Test Results report, etc.

I will close this issue once 1.7.0 is on nuget.org.

**Comment by ivanz** [comment]
The release is now. Details on the nuget package here: https://github.com/machine-visualstudio/machine.vstestadapter/releases/tag/v1.7.0

This is what it looks like (note - screenshot is of a build with a failing test):

![image](https://cloud.githubusercontent.com/assets/79742/12643061/be79a0aa-c5b1-11e5-92b5-396f5a3634a3.png)
