### ISSUE TITLE
Set-up continuous integration and nuget deployment

### ISSUE THREAD

**Issue by ivanz** [machine-visualstudio/machine.vstestadapter#23]
This task is to track the set-up of AppVeyor to:

1. Build all branches and pull requests on push/change
2. Run all tests
3. Block pull requests from being merged unless all tests pass (webhook provided by GitHub+Appveyor)
4. Manually publish the nuget package (issue #17 and pull request #22) to nuget.org from AppVeyor with a single click.
5. Add a build status badge to the GitHub page (readme)

The reason for manual nuget package push is to be able to push a version when it's deemed ready. for nuget.

@JonathanWilkins  Are you happy with this scope? Would it be possible to temporarily make me an admin of the GitHub repository, so I can set this up? Or we can pair or something? (I've done this before for some of my repo's in GitHub)

**Comment by JonathanWilkins** [comment]
All happy with that.

**Comment by JonathanWilkins** [comment]
I have added you so if you want to take a look.

**Comment by ivanz** [comment]
I have mostly finished this now - you can see it in action in here: #25

**Comment by ivanz** [comment]
https://github.com/machine-visualstudio/machine.vstestadapter/wiki/Continuous-Integration-and-Release-Process
