### ISSUE TITLE
Release 1.7.0

### ISSUE THREAD

**Issue by ivanz** [machine-visualstudio/machine.vstestadapter#28]
Hey @JonathanWilkins ,

**(Draft) Release Notes:** https://github.com/machine-visualstudio/machine.vstestadapter/releases/tag/untagged-96059f29056e1c742e1a

**Issues: https://github.com/machine-visualstudio/machine.vstestadapter/milestones/1.7.0**
 
I have created a draft 1.7.0 milestone and release on GitHub as per above. When they are done - are there any blockers to release?

**Comment by JonathanWilkins** [comment]
I don't think so would be happy for you to go ahead and release

**Comment by ivanz** [comment]
@JonathanWilkins Can you update the VSI on Visual Studio Gallery, please: https://ci.appveyor.com/api/buildjobs/t1cm41mpsclicsw5/artifacts/Source/Machine.VSTestAdapter.VSIX/bin/Release/Machine.VSTestAdapter.VSIX.vsix

**Comment by JonathanWilkins** [comment]
Haven't had to much luck with this it won't except the new version. Will keep trying
