### ISSUE TITLE
Performance: running test for the whole assembly should not be using the same code path as a single test

### ISSUE THREAD

**Issue by jonathh21** [machine-visualstudio/machine.vstestadapter#33]
Hi,

Is anyone else noticing a performance drop when using this? We changed our local and server builds to use this VS plugin, over separate mspec and msbuild runners so we have a consistent output and one trx file - which is great; really, really useful.

However, from a performance perspective we are now really struggling, and I believe it is because the the 'Establish', and 'Because' are being run for each and every 'It'. Whereas our old mspec runner ran Establish', and 'Because' once and then all the 'It's to check the assertions. 

Is this something that could be configured? 

Is anyone else experiencing this problem...

Sadly if I can't find a resolution to this my boss is gonna roll us back to separate runners :(

Thank you.

**Comment by ivanz** [comment]
Unfortunately there is no workaround currently for this. Have a look at my last comment on issue #8 for why this is currently the case. I agree - it's really not optimal at all.

**Comment by jonathh21** [comment]
Hi, I don't believe this is entirely the case - for us at least.

We are using your test adapter with vstest directly and are specify the /TestAdapterPath:

Because of the way we are using your test adapter our code entry point is RunTests sources. I can see from your code base there is a temporary 'hack' whereby you are taking the assemblies, discovering the individual tests and calling mspec for each and every one rather than just passing on the assembly name and letting the mspec runner do the magic.

I have reinstated the 'RunAssembly' call and it works fine for us... and massively improves performance, we also have about 15,000 tests of which about 8,000 are mspec and it works fine.

Does this change your understanding of our problem?

Thanks.

**Comment by ivanz** [comment]
Thanks for the clarification. I see what you mean. There is still a performance issue when using the adapter in Visual Studio, but for the CI scenario we can look to improve the code path as per your comment. I will try to have a look when I get a chance to improve that for this scenario. Meanwhile I am also working on solving the issue once and for all for all scenarios.

**Comment by jonathh21** [comment]
Awesome!

I have just finished making changes to the method myself for testing in our usage.. it is crude... but it has literally halved from 6 to 3 mins our test run times..

Total tests: 15585. Passed: 15585. Failed: 0. Skipped: 0.
Total MSTest Time: 00:03:15.8153955

```
 public void RunTests(IEnumerable<string> sources, IRunContext runContext, IFrameworkHandle frameworkHandle)
        {
            string currentAsssembly = string.Empty;

            try
            {
                ISpecificationExecutor specificationExecutor = this.adapterFactory.CreateExecutor();
                int count = sources.Count();

                foreach (var source in sources)
                {
                    currentAsssembly = source;

                    frameworkHandle.SendMessage(TestMessageLevel.Informational,
                        string.Format(Strings.EXECUTOR_EXECUTINGIN, currentAsssembly));

                    specificationExecutor.RunAssembly(currentAsssembly, MSpecTestAdapter.uri, runContext,
                        frameworkHandle);
                }

                frameworkHandle.SendMessage(TestMessageLevel.Informational, string.Format("Complete on {0} assemblies ", count));
            }
            catch (Exception ex)
            {
                frameworkHandle.SendMessage(TestMessageLevel.Error,
                    string.Format(Strings.EXECUTOR_ERROR, currentAsssembly, ex.Message));
            }
        }
```

**Comment by ivanz** [comment]
In that case - how do you feel about creating pull request for review to avoid duplication of effort? :)

**Comment by jonathh21** [comment]
I had a feeling you'd say that..... TBH I think it is worth someone who is closer to the understanding looking at what I've done above.

It is almost certainly NOT correct....

**Comment by ivanz** [comment]
It's actually fine :) :+1: I did some tiny cosmetic changes in my own pull request and will merged it.
