### ISSUE TITLE
Upload 2.0.0 to Visual Studio Extensions gallery

### ISSUE THREAD

**Issue by ivanz** [machine-visualstudio/machine.vstestadapter#55]
@JonathanWilkins  Can you please update the .vsix extension on the visual studio gallery with the one attached here: https://github.com/machine-visualstudio/machine.vstestadapter/releases/tag/v2.0.0

Release notes in the link :) Thanks!

**Comment by JonathanWilkins** [comment]
No problem will sort it out. 






On Fri, Mar 18, 2016 at 8:54 AM -0700, "Ivan Zlatev" <notifications@github.com> wrote:












@JonathanWilkins  Can you please update the .vsix extension on the visual studio gallery with the one attached here: https://github.com/machine-visualstudio/machine.vstestadapter/releases/tag/v2.0.0



Release notes in the link :) Thanks!

**Comment by JonathanWilkins** [comment]
Done.
Released Version 2.0.78 as I had to fix the ID in the manifest to get the gallery to accept it.

**Comment by ivanz** [comment]
Thanks! I have replaced the .vsix in the GitHub release with the one you uploaded to vsix gallery.
