### ISSUE TITLE
TestCaseFilter appears to be ignored.

### ISSUE THREAD

**Issue by jonathh21** [machine-visualstudio/machine.vstestadapter#58]
Any filters that are passed in seem to being ignored, 

Example: 
/TestCaseFilter:"Priority=1"
Example: /TestCaseFilter:"TestCategory=Nightly|FullyQualifiedName=Namespace.ClassName.MethodName"

Is anyone else experiencing this?

This may be related to [https://github.com/machine-visualstudio/machine.vstestadapter/issues/15](url) it may not..

**Comment by ivanz** [comment]
Closing this as duplicate of #15
