### ISSUE TITLE
Cecil should honor the <probing> element in the .dll.config to discover assemblies

### ISSUE THREAD

**Issue by jcdickinson** [machine-visualstudio/machine.vstestadapter#7]
*This also applies to the test execution: meaning we will need to handle assembly load failures in the test-run AppDomain*

**Use cases:**

- A developer may have a repository of common MSpec extensions either in a output-relative path, or at an absolute/rooted path.
- An application may have a plugin system whereby plugin assemblies are located in a sub-directory.
- At an ISV developers may be developing-on-an-actual-installation, meaning that certain references may be located in places such as "Program Files".

**Requirements:**

The developer will need to create an `App.config` for his MSpec spec project that contains paths where vstestadapter can look for assemblies:

```XML
<configuration>
  <runtime>
    <assemblyBinding>
      <probing privatePath="Plugins;C:\MyCommonSpecStuff"/>
    </assemblyBinding>
  </runtime>
</configuration>
```

This config is slightly different from the normal <probing> element in that absolute paths are also supported (this is not a problem as .Net does not honor .dll.config files).

**Sample code (contains both cases):**

https://gist.github.com/jcdickinson/5804409

**Current behavior:**

Test discovery fails. Test execution is *assumed* to fail.

**Suggested Fix:**

Update the Cecil `IAssemblyResolver` so that it also gets information from the .dll.config for the specs dll. Reuse this `IAssemblyResolver` in the test-run AppDomain to locate assemblies when the .Net runtime fails to find them.

**Comment by ivanz** [comment]
This should be fixed in 2.0.0 Beta 1: https://github.com/machine-visualstudio/machine.vstestadapter/releases/tag/v2.0.0-beta1
